import { ABILITIES } from './abilities';
import { Agent } from './agent';
import { BIOS } from './bios';
import { CONTROLLER, DUELIST, INITIATOR, SENTINEL } from './roles';
import { VIDEOS } from './videos';

export const AGENTS: Agent[] = [
  {
    id: 1,
    name: 'Brimstone',
    role: CONTROLLER,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Brimstone'),
    characterIcon: './assets/agent-photos/Brimstone.png',
    bio: BIOS[1],
    videos: VIDEOS.filter((video) => video.agentName === 'Brimstone'),
  },
  {
    id: 2,
    name: 'Phoenix',
    role: DUELIST,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Phoenix'),
    characterIcon: './assets/agent-photos/Phoenix.png',
    bio: BIOS[2],
  },
  {
    id: 3,
    name: 'Sage',
    role: SENTINEL,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Sage'),
    characterIcon: './assets/agent-photos/Sage.png',
    bio: BIOS[3],
  },
  {
    id: 4,
    name: 'Sova',
    role: INITIATOR,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Sova'),
    characterIcon: './assets/agent-photos/Sova.png',
    bio: BIOS[4],
  },
  {
    id: 5,
    name: 'Viper',
    role: CONTROLLER,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Viper'),
    characterIcon: './assets/agent-photos/Viper.png',
    bio: BIOS[5],
  },
  {
    id: 6,
    name: 'Cypher',
    role: SENTINEL,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Cypher'),
    characterIcon: './assets/agent-photos/Cypher.png',
    bio: BIOS[6],
  },
  {
    id: 7,
    name: 'Reyna',
    role: DUELIST,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Reyna'),
    characterIcon: './assets/agent-photos/Reyna.png',
    bio: BIOS[7],
  },
  {
    id: 8,
    name: 'Killjoy',
    role: SENTINEL,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Killjoy'),
    characterIcon: './assets/agent-photos/Killjoy.png',
    bio: BIOS[8],
  },
  {
    id: 9,
    name: 'Breach',
    role: INITIATOR,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Breach'),
    characterIcon: './assets/agent-photos/Breach.png',
    bio: BIOS[9],
  },
  {
    id: 10,
    name: 'Omen',
    role: CONTROLLER,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Omen'),
    characterIcon: './assets/agent-photos/Omen.png',
    bio: BIOS[10],
  },
  {
    id: 11,
    name: 'Jett',
    role: DUELIST,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Jett'),
    characterIcon: './assets/agent-photos/Jett.png',
    bio: BIOS[11],
  },
  {
    id: 12,
    name: 'Raze',
    role: DUELIST,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Raze'),
    characterIcon: './assets/agent-photos/Raze.png',
    bio: BIOS[12],
  },
  {
    id: 13,
    name: 'Skye',
    role: INITIATOR,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Skye'),
    characterIcon: './assets/agent-photos/Skye.png',
    bio: BIOS[13],
  },
  {
    id: 14,
    name: 'Yoru',
    role: DUELIST,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Yoru'),
    characterIcon: './assets/agent-photos/Yoru.png',
    bio: BIOS[14],
  },
  {
    id: 15,
    name: 'Astra',
    role: CONTROLLER,
    abilities: ABILITIES.filter((ability) => ability.agentName === 'Astra'),
    characterIcon: './assets/agent-photos/Astra.png',
    bio: BIOS[15],
  },
];
